//Dohvaćanje ne izvršenih naloga
export const FETCH_IN_PROGRESS_SERVICE_ORDERS_REQUEST =
  "FETCH_IN_PROGRESS_SERVICE_ORDERS_REQUEST";
export const FETCH_IN_PROGRESS_SERVICE_ORDERS_SUCCESS =
  "FETCH_IN_PROGRESS_SERVICE_ORDERS_SUCCESS";
export const FETCH_IN_PROGRESS_SERVICE_ORDERS_FAILURE =
  "FETCH_IN_PROGRESS_SERVICE_ORDERS_FAILURE";

//Dohvaćanje izvršenih naloga
export const FETCH_FINISHED_SERVICE_ORDERS_REQUEST =
  "FETCH_FINISHED_SERVICE_ORDERS_REQUEST";
export const FETCH_FINISHED_SERVICE_ORDERS_SUCCESS =
  "FETCH_FINISHED_SERVICE_ORDERS_SUCCESS";
export const FETCH_FINISHED_SERVICE_ORDERS_FAILURE =
  "FETCH_FINISHED_SERVICE_ORDERS_FAILURE";

//Dodavanje novog naloga
export const ADD_SERVICE_ORDER_REQUEST = "ADD_SERVICE_ORDER_REQUEST";
export const ADD_SERVICE_ORDER_SUCCESS = "ADD_SERVICE_ORDER_SUCCESS";
export const ADD_SERVICE_ORDER_FAILURE = "ADD_SERVICE_ORDER_FAILURE";

//Ažuriranje naloga
export const UPDATE_SERVICE_ORDER_REQUEST = "UPDATE_SERVICE_ORDER_REQUEST";
export const UPDATE_SERVICE_ORDER_SUCCESS = "UPDATE_SERVICE_ORDER_SUCCESS";
export const UPDATE_SERVICE_ORDER_FAILURE = "UPDATE_SERVICE_ORDER_FAILURE";

//Završi nalog
export const FINISH_SERVICE_ORDER_REQUEST = "FINISH_SERVICE_ORDER_REQUEST";
export const FINISH_SERVICE_ORDER_SUCCESS = "FINISH_SERVICE_ORDER_SUCCESS";
export const FINISH_SERVICE_ORDER_FAILURE = "FINISH_SERVICE_ORDER_FAILURE";

//Snimi fotografiju
export const TAKE_PHOTO_REQUEST = "TAKE_PHOTO_REQUEST";
export const TAKE_PHOTO_SUCCESS = "TAKE_PHOTO_SUCCESS";
export const TAKE_PHOTO_FAILURE = "TAKE_PHOTO_FAILURE";

//Printaj nalog
export const PRINT_SERVICE_ORDER_REQUEST = "PRINT_SERVICE_ORDER_REQUEST";
export const PRINT_SERVICE_ORDER_SUCCESS = "PRINT_SERVICE_ORDER_SUCCESS";
export const PRINT_SERVICE_ORDER_FAILURE = "PRINT_SERVICE_ORDER_FAILURE";

//Spremanje gotovih naloga
