//Prijava zaposlenika
export const EMPLOYEE_LOGIN_REQUEST = "EMPLOYEE_LOGIN_REQUEST";
export const EMPLOYEE_LOGIN_SUCCESS = "EMPLOYEE_LOGIN_SUCCESS";
export const EMPLOYEE_LOGIN_FAILURE = "EMPLOYEE_LOGIN_FAILURE";

//Odjava zaposlenika
export const EMPLOYEE_LOGOUT_REQUEST = "EMPLOYEE_LOGOUT_REQUEST";
export const EMPLOYEE_LOGOUT_SUCCESS = "EMPLOYEE_LOGOUT_SUCCESS";
export const EMPLOYEE_LOGOUT_FAILURE = "EMPLOYEE_LOGOUT_FAILURE";

//dohvat zaposlenika
export const FETCH_EMPLOYEES_REQUEST = "FETCH_EMPLOYEES_REQUEST";
export const FETCH_EMPLOYEES_SUCCESS = "FETCH_EMPLOYEES_SUCCESS";
export const FETCH_EMPLOYEES_FAILURE = "FETCH_EMPLOYEES_FAILURE";
